name: antap
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  shared_preferences:
  cupertino_icons: ^1.0.2
  loading_overlay: ^0.3.0
  rflutter_alert: ^2.0.7
  google_maps_flutter: ^2.5.0
  image_picker: ^0.8.5+3
  video_player: ^2.7.1
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  flutter:
    sdk: flutter
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1  
  expandable_text: ^2.2.0
  marquee: ^2.2.0
  lottie: ^1.1.9
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  english_words: ^4.0.0
  provider: ^6.0.0
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/facebook.png
    - assets/images/icons/google.png
    - assets/images/icons/linkedin.png
    - assets/images/icons/image_upload.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


